// ════════════════════════════════════════════════════════
//  CONFIGURATION & TRANSLATIONS
// ════════════════════════════════════════════════════════

export const TRANSLATIONS = {
  en: {
    viewDay:'Day', viewWeek:'Week', viewMonth:'Month', viewYear:'Year',
    today:'Today', thisPeriod:'Recurring', addTask:'＋ Add Task', addTaskShort:'ADD TASK',
    groupOnce:'One-time', week:'Week',
    newTask:'New Task', editTask:'Edit Task', task:'Task', date:'Date', repeat:'Repeat',
    recNone:'No repeat', recDaily:'Daily', recWeekly:'Weekly', recMonthly:'Monthly', recYearly:'Yearly',
    saveTask:'Save Task', cancel:'Cancel', btnAdd:'Add', btnModify:'Modify',
    frequentlyUsed:'Frequently used', recurringTasks:'Recurring tasks', recurringDaily:'Daily tasks', recurringWeekly:'Weekly tasks', recurringMonthly:'Monthly tasks', templates:'Templates', suggestedRecurring:'Suggested recurring',
    qaTitle:'Quick add', quickAddPlaceholder:'Quick add a task…',
    emptyDay:'No tasks for this day.', emptyDayAction:'Add a task', done:'done', noTasks:'No tasks',
    dayOfMonth:'Day of month:', every:'Every', repeatsEveryDay:'Repeats every day.',
    addMore:'Add', weekAdd:'+', moreTasksCount:'+{more} more',
    taskPlaceholder:'What needs to be done?',
    deleteOneOccurrence:'This occurrence only', deleteOneDesc:'Remove just this date, keep future repeats',
    deleteFutureOccurrences:'This and all future occurrences', deleteFutureDesc:'Stop repeating from this date onward',
    deleteAllOccurrences:'All occurrences', deleteAllDesc:'Delete the task entirely',
    confirmDeleteTask:'Delete this task?', selectWeekdayError:'Please select at least one day.', selectMonthDayError:'Please select at least one day or enable last day of month.', lastDayOfMonth:'Last day of month', lastDayAbbr:'end',
    confirmDeleteAllOccurrences:'Delete all occurrences of this task?',
    zoomButtonTitle:'Text size',
    exportData:'Export Data', importData:'Import Data', exportCalendar:'Export Calendar', exportConfig:'Export Settings',
    importSuccess:'Data imported successfully!', importError:'Failed to import data',
    clearAllData:'Clear all calendar data', confirmClearAllData:'Are you sure you want to clear ALL calendar data? This action is irreversible.',
    months:['January','February','March','April','May','June','July','August','September','October','November','December'],
    days:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    dayFull:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
  },
  fr: {
    viewDay:'Jour', viewWeek:'Semaine', viewMonth:'Mois', viewYear:'Année',
    today:"Aujourd'hui", thisPeriod:'Récurrent', addTask:'＋ Ajouter', addTaskShort:'AJOUTER UNE TÂCHE',
    groupOnce:'Ponctuel', week:'Semaine',
    newTask:'Nouvelle tâche', editTask:'Modifier', task:'Tâche', date:'Date', repeat:'Répétitions',
    recNone:'Aucune', recDaily:'Quotidien', recWeekly:'Hebdomadaire', recMonthly:'Mensuel', recYearly:'Annuel',
    saveTask:'Enregistrer', cancel:'Annuler', btnAdd:'Ajouter', btnModify:'Modifier',
    frequentlyUsed:'Fréquemment utilisé', recurringTasks:'Tâches récurrentes', recurringDaily:'Tâches quotidiennes', recurringWeekly:'Tâches hebdomadaires', recurringMonthly:'Tâches mensuelles', templates:'Modèles', suggestedRecurring:'Tâches suggérées',
    qaTitle:'Ajout rapide', quickAddPlaceholder:'Nouvelle tâche…',
    emptyDay:'Aucune tâche pour ce jour.', emptyDayAction:'Ajouter une tâche', done:'fait', noTasks:'Aucune tâche',
    dayOfMonth:'Jour du mois :', every:'Chaque', repeatsEveryDay:'Se répète chaque jour.',
    addMore:'Ajouter', weekAdd:'+', moreTasksCount:'+{more} de plus',
    taskPlaceholder:'Qu\'y a-t-il à faire ?',
    deleteOneOccurrence:'Cette occurrence seulement', deleteOneDesc:'Supprimer juste cette date, garder les répétitions futures',
    deleteFutureOccurrences:'Celle-ci et toutes les futures', deleteFutureDesc:'Arrêter la répétition à partir de cette date',
    deleteAllOccurrences:'Toutes les occurrences', deleteAllDesc:'Supprimer la tâche entièrement',
    confirmDeleteTask:'Supprimer cette tâche ?', selectWeekdayError:'Veuillez sélectionner au moins un jour.', selectMonthDayError:'Veuillez sélectionner au moins un jour ou activer le dernier jour du mois.', lastDayOfMonth:'Dernier jour du mois', lastDayAbbr:'fin',
    confirmDeleteAllOccurrences:'Supprimer toutes les occurrences de cette tâche ?',
    zoomButtonTitle:'Taille du texte',
    exportData:'Exporter les données', importData:'Importer les données', exportCalendar:'Exporter le calendrier', exportConfig:'Exporter les paramètres',
    importSuccess:'Données importées avec succès !', importError:'Échec de l\'importation',
    clearAllData:'Vider toutes les données du calendrier', confirmClearAllData:'Êtes-vous sûr de vouloir vider TOUTES les données du calendrier ? Cette action est irréversible.',
    months:['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
    days:['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'],
    dayFull:['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi']
  },
  es: {
    viewDay:'Día', viewWeek:'Semana', viewMonth:'Mes', viewYear:'Año',
    today:'Hoy', thisPeriod:'Este período', addTask:'＋ Agregar',
    groupOnce:'Único', week:'Semana',
    newTask:'Nueva tarea', task:'Tarea', date:'Fecha', repeat:'Repetir',
    recNone:'Sin repetición', recDaily:'Diario', recWeekly:'Semanal', recMonthly:'Mensual', recYearly:'Anual',
    saveTask:'Guardar', cancel:'Cancelar',
    frequentlyUsed:'Usadas frecuentemente', recurringTasks:'Tareas recurrentes', recurringDaily:'Tareas diarias', recurringWeekly:'Tareas semanales', recurringMonthly:'Tareas mensuales', templates:'Plantillas', suggestedRecurring:'Tareas sugeridas',
    qaTitle:'Añadir rápido', quickAddPlaceholder:'Añadir una tarea… (Enter para guardar)',
    emptyDay:'No hay tareas para este día.', emptyDayAction:'Agregar una tarea', done:'hechas', noTasks:'Sin tareas',
    dayOfMonth:'Día del mes:', every:'Cada', repeatsEveryDay:'Se repite todos los días.',
    addMore:'Agregar',
    clearAllData:'Borrar todos los datos del calendario', confirmClearAllData:'¿Está seguro de que desea borrar TODOS los datos del calendario? Esta acción es irreversible.',
    months:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
    days:['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],
    dayFull:['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado']
  },
  de: {
    viewDay:'Tag', viewWeek:'Woche', viewMonth:'Monat', viewYear:'Jahr',
    today:'Heute', thisPeriod:'Dieser Zeitraum', addTask:'＋ Hinzufügen',
    groupOnce:'Einmalig', week:'Woche',
    newTask:'Neue Aufgabe', task:'Aufgabe', date:'Datum', repeat:'Wiederholen',
    recNone:'Keine Wiederholung', recDaily:'Täglich', recWeekly:'Wöchentlich', recMonthly:'Monatlich', recYearly:'Jährlich',
    saveTask:'Speichern', cancel:'Abbrechen',
    frequentlyUsed:'Häufig verwendet', recurringTasks:'Wiederkehrende Aufgaben', recurringDaily:'Tägliche Aufgaben', recurringWeekly:'Wöchentliche Aufgaben', recurringMonthly:'Monatliche Aufgaben', templates:'Vorlagen', suggestedRecurring:'Vorgeschlagene Aufgaben',
    qaTitle:'Schnell hinzufügen', quickAddPlaceholder:'Aufgabe hinzufügen… (Enter zum Speichern)',
    emptyDay:'Keine Aufgaben für diesen Tag.', emptyDayAction:'Aufgabe hinzufügen', done:'erledigt', noTasks:'Keine Aufgaben',
    dayOfMonth:'Tag des Monats:', every:'Jeden', repeatsEveryDay:'Wiederholt sich täglich.',
    addMore:'Hinzufügen',
    clearAllData:'Alle Kalenderdaten löschen', confirmClearAllData:'Sind Sie sicher, dass Sie ALLE Kalenderdaten löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    months:['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],
    days:['So','Mo','Di','Mi','Do','Fr','Sa'],
    dayFull:['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag']
  }
};

export const ZOOM_SIZES = [13, 16, 20]; // S, M, L
